apiVersion: v1
kind: Pod
metadata:
  name: defvpod
  labels:
         env: dev
         dc: India
spec:
     containers:
              - name: "pod1"
                image: "vimal13/apache-webserver-php"
                volumeMounts:
                   - name: defaultvol
                     mountPath: /var/www/html
     volumes:
              - name: defaultvol    
                persistentVolumeClaim:
                 claimName: defaultpvc