apiVersion: apps/v1
kind: ReplicaSet
metadata:
      name: rspvc1
spec:
     replicas: 1
     selector:
          matchLabels:
                 env: dev
          matchExpressions:
                 - { key : env, operator: In, values: [dev] }
     template:
           metadata:
                 name: pod1
                 labels:
                      env: dev
           spec:
               containers:
                - name: "volumec1"
                  image: "vimal13/apache-webserver-php"
                  volumeMounts:
                     - name: web-v1
                       mountPath: /var/www/html
               volumes:
                 - name: web-v1
                   persistentVolumeClaim:
                         claimName: vc1    