apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: wordpress

spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
      app: wp
  template:
    metadata:
      name: wppod1
      labels:
        env: dev
        app: wp
    spec:
      containers:
      - name: "wordpress"
        image: "wordpress:4.8-apache"


