apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
         name: vgcluster
         region: us-east-1

nodeGroups:
  - name: ng1
    instanceType: t2.micro
    desiredCapacity: 3
    ssh:
      publicKeyName: ekskey
  