apiVersion: v1
kind: Service
metadata:
       name: nodeportservice
spec:
     selector:
               dc: IN
     type: NodePort
     ports:
        - port: 8080
          targetPort: 80
          nodePort: 31000 