apiVersion: apps/v1
kind: ReplicaSet
metadata:
         name: replicaset1

spec:
   replicas: 2
   selector:
        matchLabels:
          env: dev
          
   template:
        metadata:
             name: pod1
             labels:
                  env: dev
        spec:
             containers:
             - name: "sqlimg"
               image: "mysql:5.6"
               env:
               - name: MYSQL_ROOT_PASSWORD
                 value: garg
               - name: MYSQL_DATABASE
                 value: garg
               - name: MYSQL_USER
                 value: vanshika
               - name: MYSQL_PASSWORD
                 value: sroot
             
