apiVersion:  v1
kind: Pod
metadata:
       name: pod1
       labels:
        env: dev
        dc: IN
spec:
      containers:
      - name: "smallimage"
        image: "vimal13/apache-webserver-php"
      restartPolicy: Always
