apiVersion: v1
kind: ReplicationController
metadata:
         name: rc1

spec:
   replicas: 2
   selector:
          env: dev
          dc: IN
   template:
        metadata:
             name: pod1
             labels:
                  env: dev
                  dc: IN
        spec:
             containers:
             - name: "smallimage"
               image: "vimal13/apache-webserver-php"
             restartPolicy: Always
